### ISSUE TITLE
Locale bug with non standard system locales...

### ISSUE THREAD

**Issue by 0r31** [dagoma3d/CuraByDagoma#130]
OS : Microsoft Windows 10 Pro UK
Version : 10.0.19044 Build 19044 (21H2)

```console
Traceback (most recent call last):
File "C:\Program Files\CuraByDagoma\python3\lib\runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "C:\Program Files\CuraByDagoma\python3\lib\runpy.py", line 87, in _run_code
exec(code, run_globals)
File "C:\Program Files\CuraByDagoma\Cura\cura.py", line 122, in <module>
main()
File "C:\Program Files\CuraByDagoma\Cura\cura.py", line 119, in main
app.CuraApp(args).MainLoop()
File "C:\Program Files\CuraByDagoma\Cura\gui\app.py", line 60, in __init__
self.splash = splashScreen.splashScreen(self.afterSplashCallback)
File "C:\Program Files\CuraByDagoma\Cura\gui\splashScreen.py", line 11, in __init__
bitmap = wx.Bitmap(getPathForImage('splash.png'))
wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(0, 0), "C") == 0" failed at ..\..\src\common\intl.cpp(1694) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!
```

Same kind of bugs : 
https://github.com/MicronOxford/cockpit/issues/658
https://github.com/wxphp/wxphp/issues/108

Potential workaround :
https://discuss.wxpython.org/t/wxpython4-1-1-python3-8-locale-wxassertionerror/35168/3
https://discuss.wxpython.org/t/questions-on-the-locale-issue/36084

Implementation in wxPython :
https://github.com/wxWidgets/Phoenix/commit/040c59fd991cd08174b5acee7de9418c23c9de33

Discussion regarding setLocale() on Python bug tracking tool :
https://bugs.python.org/issue43115

**Comment by 0r31** [comment]
How to reproduce ? On Windows, change locale params to :
- Contry or region: United Kingdom
- Regional format: English (Europe)

**Comment by 0r31** [comment]
Fixed by https://github.com/dagoma3d/CuraByDagoma/commit/bed4e190ee8aeb755c220571350fd1de2f7f4d72
