### ISSUE TITLE
Numpy memory error - python3

### ISSUE THREAD

**Issue by 0r31** [dagoma3d/CuraByDagoma#6]
Reported by a customer for working on Linux with some STLs.

Trace:

```
Traceback (most recent call last):
  File "/usr/share/curabydago/Cura/gui/sceneView.py", line 739, in loadScene
    objList = meshLoader.loadMeshes(filename)
  File "/usr/share/curabydago/Cura/util/meshLoader.py", line 32, in loadMeshes
    return stl.loadScene(filename)
  File "/usr/share/curabydago/Cura/util/meshLoaders/stl.py", line 61, in loadScene
    _loadBinary(m, f)
  File "/usr/share/curabydago/Cura/util/meshLoaders/stl.py", line 45, in _loadBinary
    m._prepareFaceCount(faceCount)
  File "/usr/share/curabydago/Cura/util/printableObject.py", line 328, in _prepareFaceCount
    self.vertexes = numpy.zeros((faceNumber*3, 3), numpy.float32)
MemoryError

```

**Comment by 0r31** [comment]
The PR #9 fixes this issue.
