### ISSUE TITLE
Sauvegarde du plateau impossible

### ISSUE THREAD

**Issue by 0r31** [dagoma3d/CuraByDagoma#84]
La fonctionnalité "sauvegarder le plateau" (accessible depuis le menu principal, Fichier > Sauvegarder le plateau) est cassée
Le fichier stl final est vide.

**Comment by 0r31** [comment]
```
Traceback (most recent call last):
  File "C:\Program Files\CuraByDagoma\Cura\gui\mainWindow.py", line 74, in <lambda>
    self.Bind(wx.EVT_MENU, lambda e: self.scene.showSaveModel(), i)
  File "C:\Program Files\CuraByDagoma\Cura\gui\sceneView.py", line 293, in showSaveModel
    meshLoader.saveMeshes(filename, self._scene.objects())
  File "C:\Program Files\CuraByDagoma\Cura\util\meshLoader.py", line 48, in saveMeshes
    stl.saveScene(filename, objects)
  File "C:\Program Files\CuraByDagoma\Cura\util\meshLoaders\stl.py", line 69, in saveScene
    saveSceneStream(f, objects)
  File "C:\Program Files\CuraByDagoma\Cura\util\meshLoaders\stl.py", line 74, in saveSceneStream
    stream.write(("CURA BINARY STL EXPORT. " + time.strftime('%a %d %b %Y %H:%M:%S')).ljust(80, '\000'))
TypeError: a bytes-like object is required, not 'str'
````
